name: Podcast Feed
on:
  push:
    branches: ["production"]
  workflow_dispatch:
  schedule:
    # Runs everyday
    - cron: '0 0 * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest podcast episode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://craveiro.com.br/podcast/feed/"
